version: '3'
 
services:
  db_tp01:
    image: mysql:5.7
    container_name: db_tp01
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: ynov
      MYSQL_USER: admin
      MYSQL_PASSWORD: KS9zSb3lspMpq
    ports:
      - "6033:3306"
    volumes:
      - dbdata_tp01:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmy_tp01
    links:
      - db_tp01
    environment:
      PMA_HOST: db_tp01
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8082:80
volumes:
  dbdata_tp01: